image: clever/drone-go:1.6
notify:
  email:
    recipients:
    - drone@clever.com
publish:
  catapult:
    url: $$catapult_url
    application: graphviz-service
  docker:
    docker_host: $$docker_server
    email: $$docker_email
    image_name: clever/graphviz-service
    password: $$docker_password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$docker_username
    when:
      branch: master
  report_card: {}
script:
- make test
- make build
